# Generated by Django 4.2.7 on 2023-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("slug", models.SlugField(blank=True, max_length=60)),
                ("birthdate", models.DateField()),
                ("city", models.CharField(max_length=30)),
                ("hobbies", models.TextField()),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="competitors/%Y/%m/%d/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("slug", models.SlugField(blank=True, max_length=60)),
                ("avatar", models.ImageField(blank=True, upload_to="judges/%Y/%m/%d/")),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("slug", models.SlugField(blank=True, max_length=60)),
                (
                    "avatar",
                    models.ImageField(blank=True, upload_to="teachers/%Y/%m/%d/"),
                ),
            ],
        ),
    ]
