# Generated by Django 4.2.7 on 2023-11-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='job',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='judge',
            name='job',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('REW', 'Review'), ('CHP', 'Choreography'), ('FIT', 'Fitness'), ('YOG', 'Yoga'), ('MDR', 'Musical Director'), ('VTC', 'Vocal technique'), ('UDC', 'Urban Dance'), ('ENG', 'English'), ('CSG', 'Choral Singing'), ('INT', 'Interpretation')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='judge',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='judge/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='style',
            field=models.ManyToManyField(to='info.musicstyle'),
        ),
    ]
