# Generated by Django 4.2.7 on 2023-11-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_musicstyle_competitor_job_judge_job_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('REW', 'Review'), ('CHP', 'Choreography'), ('FIT', 'Fitness'), ('YOG', 'Yoga'), ('MDR', 'Musical Director'), ('VTC', 'Vocal technique'), ('UDC', 'Urban Dance'), ('ENG', 'English'), ('CSG', 'Choral Singing'), ('INT', 'Interpretation')], max_length=3, null=True),
        ),
    ]
