# Generated by Django 4.2.7 on 2023-11-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='style',
            field=models.ManyToManyField(related_name='style', to='info.musicstyle'),
        ),
    ]
