# Generated by Django 4.2.7 on 2023-11-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_competitor_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='job',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='style',
            field=models.ManyToManyField(to='info.musicstyle'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='job',
            field=models.CharField(max_length=30),
        ),
    ]
