# Generated by Django 4.2.7 on 2023-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_competitor_job_alter_competitor_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='curious_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='favourite_singer_song',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='job',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='slug',
            field=models.SlugField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='judge',
            name='job',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='musicstyle',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
