# Generated by Django 4.2.7 on 2023-11-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_competitor_curious_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
