# Generated by Django 4.2.7 on 2023-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_competitor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('REW', 'Repaso'), ('CHP', 'Coreografía'), ('FIT', 'Fitness'), ('YOG', 'Yoga'), ('MDR', 'Dirección Musical'), ('VTC', 'Técnica Vocal'), ('UDC', 'Baile Urbano'), ('ENG', 'Inglés'), ('CSG', 'Canto Coral'), ('INT', 'Interpretación')], max_length=3, null=True),
        ),
    ]
