# Generated by Django 4.2.7 on 2023-12-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
