# Generated by Django 4.2.7 on 2023-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_competitor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicstyle',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='musicstyle',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
