# Generated by Django 4.2.7 on 2023-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_musicstyle_name_alter_musicstyle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='competitors/%Y/%m/%d/'),
        ),
    ]
